### ISSUE TITLE
Compliance check

### ISSUE THREAD

**Issue by nyirit** [SCOAP3/scoap3-next#2]
Automatic compliance check for incoming records.

Admin interface:
- [x] Create an interface for reviewing and modifying automatic results.
- [x] Create an aggregated view with information about the processes in the last days.

Run compliance check:
- [x] Check pdf and pdfa files as well
- [x] Create a detailed view of a record
- [x] Add automatic compliance checks to the harvest process
- [x] Check for the following: 
  - [x] publication is not older than 24h
  - [x] has "Founded by SCOAP3" marking (pdf(a) parse)
  - [x] has author rights: ? (pdf(a) parse)
  - [x] has 'cc-by', 'cc by' or 'creative commons attribution' (pdf(a) parse)
  - [x] has the necessary files: .xml, .pdf, .pdfa
  - [ ] ~~right arXiv category~~ (already done in article_upload)

**Comment by Dziolas** [comment]
### Compliance done on the metadata:
- license type (CC-BY) is stored in the metadata
- information like "Copyright the authors" should be partialy in metadata (varays between publishers)
- 24h delivery check with usage of Crossref

### Compliance done on the PDF (and on XML if you find it useful):
- license type
- copyright information
- "Funded by SCOAP3" text

### Checking 24h delivery
Take a look at the Crossref API documentation is here: https://github.com/CrossRef/rest-api-doc

What can be usefull for you is how to fetch a single article metadata from them. Here is an example: https://api.crossref.org/works/10.1155/2018/4672051 (https://api.crossref.org/works/ + articles DOI from our record's metadata).

You might wanna store the time difference between the Crossref API data and our delivery information. I don't remember if there is a reasonable date in the metadata so if you will have problem decidning which is the correct datetime of delivery in our repo to use, you can use the creation date of the Record object.

### Future things
- checking if PDF from publisher site is the same as ours
- checking if information on the publishers website are correct

**Comment by nyirit** [comment]
### PDF check with fuzzy regex:
With fuzzy regex it's easier to find phrases in pdf, since it can be configured to tolerate faults e.g. syllabication, but it also can take a lot more time in our cases. Python regex lib supports this feature. 
#### Performance test details:
- Base pattern: `.{0,10}creative.?commons.?attribution.{0,10}`
- Used pdf: `10.1140_epjc_s10052-018-6183-4.pdf` (13 pages)
- Number of executions: 10
- Showed values are average execution times in sec
- (ix): fuzzy regex with maximum x insertions
- (ex): fuzzy regex with maximum x errors (errors can be insertion, deletion or substiution)
#### Results:
```
       re.findall: 0.00985481739044
regex.findall(e1): 0.146906089783
regex.findall(e3): 1.22483680248
regex.findall(e5): 11.1781222105
regex.findall(i1): 0.151753306389
regex.findall(i3): 0.227966213226
regex.findall(i5): 0.310106110573
        re.search: 0.00685188770294
 regex.search(e1): 0.0857359170914
 regex.search(e3): 0.594110703468
```

**Comment by Dziolas** [comment]
Done :)
