### ISSUE TITLE
Fix harvesting

### ISSUE THREAD

**Issue by oxmynx** [SCOAP3/scoap3-next#240]
Since June 3rd, no new articles were harvested or at least are visible in the repo. This needs urgent investigation and fixing.

**Comment by nyirit** [comment]
Issues were:

- the password for scoap3ra user changed, but the keytab file was not updated.
- eos path changed, but the config used the old one for which it didn't have permission.
- seems to have been a stuck harvest running for weeks, this stopped other harvests of running.

**Comment by nyirit** [comment]
So far the general harvest issues are fixed.
