### ISSUE TITLE
Review SCOAP3 machines

### ISSUE THREAD

**Issue by oxmynx** [SCOAP3/scoap3-next#244]
To support the ongoing upgrade of servers, Ben needs support identifying the different machines used by SCOAP3 and their relevance to todays production environment.

**Comment by nyirit** [comment]
We've talked about the machines on Slack.

All information is present in the documentation: https://scientific-information-service.web.cern.ch/scientific-information-service/SIS.%20SCOAP3/SCOAP3%20Repository/Operations/
I don't have any knowledge of servers not listed here, so most probably those can be deleted without any issue. These had been created before I came to CERN and are not documented.

Only the following machines are used: scoap3-web1, scoap3-web2, scoap3-lb1, scoap3-task1, scoap3-builder1 and scoap3-mq1.
