### ISSUE TITLE
Published Online Date

### ISSUE THREAD

**Issue by oxmynx** [SCOAP3/scoap3-next#245]
Articles harvested have inconsistent dates and hence are assigned to years in an inconsistent way. The aim should be to use official publications dates, e.g. First Available Online in CrossRef. The availability of these dates needs to be investigated and a workflow established that these dates are used in the repository for search and display. If not available for all journals, a pragmatic solution needs to be discussed with the operations manager.

**Comment by nyirit** [comment]
The main issue is covered in #256, but additional investigation would be great to see if there is any other article with an incorrect publication date. Maybe even a general check could be implemented?
