### ISSUE TITLE
Add missing CPC articles

### ISSUE THREAD

**Issue by nyirit** [SCOAP3/scoap3-next#257]
There are currently around 20 missing articles since 1 May due to the major harvest outage (which is already fixed).

**Comment by nyirit** [comment]
OUP CPC articles are still missing, the rest is fixed.

**Comment by nyirit** [comment]
Only the 10 CPC article is missing, an email to the publisher is needed.

**Comment by jelenabrankovic** [comment]
This should be closed - although new 2021 articles are missing
