### ISSUE TITLE
Article year captured wrongly in Repo

### ISSUE THREAD

**Issue by jelenabrankovic** [SCOAP3/scoap3-next#337]
Some articles are wrongly showing as 2020 but are in reality 2021. This is partially a problem related to the different metadata that publishers send. 
Mainly the problem is PTEP (this happened before with them) where we know they register the DOI very early, so we counted some 2021 articles for 2020. Example: 
https://academic.oup.com/ptep/article/2021/2/023B01/6055559
This PTEP articles is officially published in December 2020, but the article belongs to volume in February 2021. 
Our repository puts as "year" = 2020 and it should be 2021.

We also have some slight differences for EPJC, JHEP and PLB due to the same reason.

**Comment by drjova** [comment]
@agentilb do the provide any metadata that indicates the articles is 2021?

**Comment by agentilb** [comment]
2020 is indeed here the ePub date:  
```
<pub-date pub-type="epub" iso-8601-date="2020-12-30">
<day>30</day>
<month>12</month>
<year>2020</year>
</pub-date>
```

But indeed, this article is actually in the 2021 volume:
We have it in the metadata here: 
`<pub-date pub-type="collection" iso-8601-date="2021-02-11"><day>11</day><month>02</month><year>2021</year></pub-date>`
`<volume>2021</volume><issue>2</issue>`

**Comment by ErnestaP** [comment]
Changes are deployed in QA, example with the same article is the following: https://repo.qa.scoap3.org/records/60075
@jelenabrankovic  or @agentilb  Could you please confirm, that result is as expected? :)

**Comment by agentilb** [comment]
Thank you @ErnestaP if I understand correctly, you changed the way `publication_info.year` is filled? Is that correct?

**Comment by ErnestaP** [comment]
yes

**Comment by agentilb** [comment]
Yes, the change is correct. You can deploy the change. Thanks a lot!

**Comment by ErnestaP** [comment]
To be more precise: the _year_ was changed to _volume_ value. As I understand volume is: "The volume number of a journal, or any other periodical text, refers to the number of years the text has been in publication. For example, all issues of a journal released in its third year of publication would be categorized under volume three". In our case, we have a volume as the year when the article was published in OUP. Is it makes sense?

**Comment by agentilb** [comment]
Well, the definition of volume is not really correct here, since there can be several volumes per year. 
But it works indeed for PTEP. 
It won't work anymore if PTEP would decide to number their volumes differently.
