### ISSUE TITLE
Missing DOIS

### ISSUE THREAD

**Issue by drjova** [SCOAP3/scoap3-next#339]

**Comment by ErnestaP** [comment]
10.1093/ptep/ptab050
10.1093/ptep/ptab052
10.1093/ptep/ptab130
10.1093/ptep/ptab133
10.1093/ptep/ptab143
10.1093/ptep/ptab134
10.1093/ptep/ptab141
10.1093/ptep/ptab142
10.1093/ptep/ptab144
10.1093/ptep/ptab147

**Comment by drjova** [comment]
All of the DOIS are in the repo.
