### ISSUE TITLE
Author export on SCOAP3 repo not working for some time 

### ISSUE THREAD

**Issue by jelenabrankovic** [SCOAP3/scoap3-next#342]
One of the main exports SCOAP3 team provides for partners is a list of DoIs of published articles per institution per author. It is usually a very large file and since few months it completely stopped working.

**Comment by drjova** [comment]
@jelenabrankovic could you please give us more details where is this tool?

**Comment by jelenabrankovic** [comment]
SCOAP3 repository - On the user profile's drop menu in the right upper corner, one can find the feature "Tools". The click takes to a tool for 2 types of exports (both per country and per year) 1. Affiliations (Gives a list of all institutions per DoI in a country, number of authors of that article in the institution, and total number of articles) and 2. Author export (Gives one line per each of the authors of each article, per institute in a country)

**Comment by agentilb** [comment]
We received today an error message, someone who tried to do an affiliation export, and it created an error: 

<img width="918" alt="Screenshot 2022-02-07 at 16 44 00" src="https://user-images.githubusercontent.com/12181904/152821521-43afde80-5e76-40e3-839e-fc4850adff47.png">

Message:
```
Dear User,
There was a request made on https://repo.scoap3.org/ using your email address to export article data from our repository.

We are sorry, but an unexpected error occurred while generating the requested data. If this issue persists please do not hesitate to contact us by replying to this email.

Debug information: f48ef661-b57f-4582-9053-a8bc9b0d61ba With kind regards,
The SCOAP3 Team

```

**Comment by ErnestaP** [comment]
Dear @agentilb ,
Can you please provide the year and country which were entered as input?

**Comment by agentilb** [comment]
Hi @ErnestaP this was an email we received. I don't know what the user had selected. Can you not find out from the logs?

**Comment by drjova** [comment]
@agentilb After checking the logs, it's a user error, they tried to export with an empty affiliation. We'll close this issue for now, if this happens again please ask the user for more details.

**Comment by agentilb** [comment]
Just did a try myself on an affiliation export "CERN" "2021", and I got an error message: 

Dear User,
There was a request made on https://repo.scoap3.org/ using your email address to export article data from our repository.

We are sorry, but an unexpected error occurred while generating the requested data. If this issue persists please do not hesitate to contact us by replying to this email.

Debug information: fef10fcf-8792-4c6a-94d5-a923f15687ae With kind regards,
The SCOAP3 Team

**Comment by agentilb** [comment]
Ignore my last comment, it was indeed an empty field error as well.
