### ISSUE TITLE
PTEP issue

### ISSUE THREAD

**Issue by jelenabrankovic** [SCOAP3/scoap3-next#343]
Communication :
29th December 2021 :
<img width="757" alt="Screenshot 2022-01-17 at 11 25 38" src="https://user-images.githubusercontent.com/45336113/149752403-217f9373-e1d0-4798-ae45-275231dfa579.png">

7 January 2022 & 11 January 2022: 
"Issue 12 of PTEP published on December 29th and our typesetter has confirmed that they uploaded the necessary SCOAP3 packages to the usual FTP on the same day. We have also resupplied the same data on January 5th but neither deposits are reflected in the repository.
 
Would you please be able to investigate and let us know if there are any problems on your end/issues with the data received?

The DOI’s of the papers that our supplier has tried to deposit are:
 
10.1093/ptep/ptab050
10.1093/ptep/ptab052
10.1093/ptep/ptab130
10.1093/ptep/ptab133
10.1093/ptep/ptab143
10.1093/ptep/ptab134
10.1093/ptep/ptab141
10.1093/ptep/ptab142
10.1093/ptep/ptab144
10.1093/ptep/ptab147
 
We have recently switched to a new service provider and this is their first deposit for us, so the error could be a very basic one. We have provided them with detailed instructions that we believe have been followed correctly and have verified that the files were submitted to the FTP correctly."

**Comment by drjova** [comment]
Supersede by #339
