### ISSUE TITLE
APS 2021 Articles Missing 

### ISSUE THREAD

**Issue by jelenabrankovic** [SCOAP3/scoap3-next#359]
Here are the missing PRD articles:
- [x] 10.1103/PhysRevD.104.032009
- [X] 10.1103/PhysRevD.104.033004
- [X] 10.1103/PhysRevD.104.033005
- [X] 10.1103/PhysRevD.104.034026
- [X] 10.1103/PhysRevD.104.035024
- [X] 10.1103/PhysRevD.104.035025
- [X] 10.1103/PhysRevD.104.035026
- [X] 10.1103/PhysRevD.104.036012
- [X] 10.1103/PhysRevD.104.044064
- [X] 10.1103/PhysRevD.104.045015
- [X] 10.1103/PhysRevD.104.046025
 
 Here are the missing PRL articles:
- [x] 10.1103/PhysRevLett.127.051802
- [X] 10.1103/PhysRevLett.127.092301

**Comment by drjova** [comment]
All the missing articles are now in the repo
