### ISSUE TITLE
Internal server error on export search results

### ISSUE THREAD

**Issue by agentilb** [SCOAP3/scoap3-next#364]
On https://repo.scoap3.org/search?page=1&size=20&journal=Chinese%20Physics%20C&year=2021--2022
I want to export the list of records from the search page, clicking on the result number: 
<img width="1242" alt="Screenshot 2022-02-28 at 11 11 57" src="https://user-images.githubusercontent.com/12181904/155965001-2551317a-a667-4947-a1ef-1ccaf9a7e96d.png">
I get an Internal Server Error:
<img width="1242" alt="Screenshot 2022-02-28 at 11 12 27" src="https://user-images.githubusercontent.com/12181904/155965037-be552cd6-e5ca-4da3-a26e-626f5ebe69dd.png">

**Comment by drjova** [comment]
It's fixed
