### ISSUE TITLE
Halted articles on the repo

### ISSUE THREAD

**Issue by jelenabrankovic** [SCOAP3/scoap3-next#369]
SCOAP3 repository-workflow- halted articles
We received suddenly halted articles with completely empty error message, so we don't know why they are halted

**Comment by agentilb** [comment]
Some details about this: 
On 28/02, 01/03, 02/03 and 03/03 we received many messages for Halted articles. 
But those are not always visible on the admin interface. 
https://repo.scoap3.org/admin/workflow/?flt1_21=2

Ex. 
<img width="1201" alt="Screenshot 2022-03-04 at 11 01 42" src="https://user-images.githubusercontent.com/12181904/156742430-102664f6-7561-49c5-88cd-5f04e627cfbe.png">

In the admin interface, we see also some halted articles with no details: 
<img width="1201" alt="Screenshot 2022-03-04 at 11 03 18" src="https://user-images.githubusercontent.com/12181904/156742767-1a821d4b-6e10-4d0a-bfcf-027dcc276d8a.png">

**Comment by drjova** [comment]
@agentilb if you click in edit, you can see the errors in detailed. Please let me know if you have any questions.

**Comment by drjova** [comment]
It's fixed.
