### ISSUE TITLE
Missing IOP articles

### ISSUE THREAD

**Issue by agentilb** [SCOAP3/scoap3-next#375]
These 6 DOIs were in the list sent by IOP on 21/02, but are not visible publicly on the repository:

10.1088/1674-1137/ac1575
10.1088/1674-1137/ac1577
10.1088/1674-1137/abdfbd
10.1088/1674-1137/ac3122
10.1088/1674-1137/ac3124
10.1088/1674-1137/ac338e

Could you check if they have been received?

**Comment by ErnestaP** [comment]
Yes, we received all of them. 
Attacking all DOIs we have of IOP in production. Checking now, why we don't see them on the repo.
[IOP_all_articles_in_prod.txt](https://github.com/SCOAP3/scoap3-next/files/8221783/IOP_all_articles_in_prod.txt)

**Comment by ErnestaP** [comment]
Fixed :)
