### ISSUE TITLE
3 articles from March issue uploaded on 11/03/2022 on the FTP server by OUP not yet appearing on the repo

### ISSUE THREAD

**Issue by agentilb** [SCOAP3/scoap3-next#386]
![image001](https://user-images.githubusercontent.com/12181904/158345546-9c66f9f3-3ee9-4456-a873-4ffeb62447ae.png)

List of articles:
 
Ptab019
Ptac028
Ptac031

**Comment by agentilb** [comment]
Zip file of the articles, in case it is needed
[SCOAP_March_BatchIV.zip](https://github.com/SCOAP3/scoap3-next/files/8252318/SCOAP_March_BatchIV.zip)

**Comment by ErnestaP** [comment]
Anne, are you sure that articles are ptaB? Are they or not ptaC?

**Comment by ErnestaP** [comment]
10.1093/ptep/ptab019
10.1093/ptep/ptac028
10.1093/ptep/ptac031

These articles are in repo now

**Comment by agentilb** [comment]
I copied the info received from OUP in the email, but indeed in the zip file, they are all ptac. 
So they should be: 
```
Ptac019
Ptac028
Ptac031
```

**Comment by drjova** [comment]
@ErnestaP can we close the issue?

**Comment by agentilb** [comment]
Yes, everything is in order.
