### ISSUE TITLE
Clean pending tasks

### ISSUE THREAD

**Issue by ErnestaP** [SCOAP3/scoap3-next#395]

**Comment by drjova** [comment]
@benjamin-bergia could we check if we get OOM in the workers in scoap3 prod?

**Comment by benjamin-bergia** [comment]
I checked and there was no OOM kill

**Comment by drjova** [comment]
Did you check for an extended period?

**Comment by benjamin-bergia** [comment]
7 days

**Comment by drjova** [comment]
Can we check for the last month?

**Comment by benjamin-bergia** [comment]
I will. Also all the pods have 0 restarts
