### ISSUE TITLE
OUP March issue

### ISSUE THREAD

**Issue by agentilb** [SCOAP3/scoap3-next#398]
Articles received on 28/03:

![image001](https://user-images.githubusercontent.com/12181904/160653330-e7e47e18-911e-4b54-8fa5-912970ac49ce.png)

List of articles: 
Ptac022
Ptac035

**Comment by agentilb** [comment]
![image002-2022](https://user-images.githubusercontent.com/12181904/161214401-89ead1a0-1b33-4021-92d8-528bff8cbc02.png)

List of articles:
Ptac040

**Comment by drjova** [comment]
@agentilb are we sure about `Ptac022` and `Ptac035`? I only see `Ptac040` in the recent files.

**Comment by agentilb** [comment]
Are the files still automatically deleted from the FTP server?
Can it be that the first harvest (with `Ptac022` and `Ptac035`)  went wrong and the zip file was automatically deleted?
