### ISSUE TITLE
APS Missing article

### ISSUE THREAD

**Issue by agentilb** [SCOAP3/scoap3-next#402]
There were a few discrepancies between APS' report and CERN's repository for March.

Three PRC articles in APS' report were not included in CERN's repository:
10.1103/PhysRevC.105.034901
10.1103/PhysRevC.105.034902
10.1103/PhysRevC.105.L032201

Fifty-nine PRD articles in APS' report were not included in CERN's repository:
10.1103/PhysRevD.105.052002
10.1103/PhysRevD.105.052006
10.1103/PhysRevD.105.052007
10.1103/PhysRevD.105.053006
10.1103/PhysRevD.105.053007
10.1103/PhysRevD.105.054002
10.1103/PhysRevD.105.054003
10.1103/PhysRevD.105.054005
10.1103/PhysRevD.105.054006
10.1103/PhysRevD.105.054017
10.1103/PhysRevD.105.054018
10.1103/PhysRevD.105.054019
10.1103/PhysRevD.105.054020
10.1103/PhysRevD.105.054021
10.1103/PhysRevD.105.054022
10.1103/PhysRevD.105.054023
10.1103/PhysRevD.105.054502
10.1103/PhysRevD.105.054503
10.1103/PhysRevD.105.054504
10.1103/PhysRevD.105.054509
10.1103/PhysRevD.105.054510
10.1103/PhysRevD.105.055002
10.1103/PhysRevD.105.055004
10.1103/PhysRevD.105.055005
10.1103/PhysRevD.105.055007
10.1103/PhysRevD.105.055008
10.1103/PhysRevD.105.055013
10.1103/PhysRevD.105.055014
10.1103/PhysRevD.105.055015
10.1103/PhysRevD.105.056001
10.1103/PhysRevD.105.056002
10.1103/PhysRevD.105.056003
10.1103/PhysRevD.105.056004
10.1103/PhysRevD.105.056005
10.1103/PhysRevD.105.056006
10.1103/PhysRevD.105.056007
10.1103/PhysRevD.105.056008
10.1103/PhysRevD.105.056013
10.1103/PhysRevD.105.056014
10.1103/PhysRevD.105.062003
10.1103/PhysRevD.105.063509
10.1103/PhysRevD.105.064006
10.1103/PhysRevD.105.064015
10.1103/PhysRevD.105.065002
10.1103/PhysRevD.105.065004
10.1103/PhysRevD.105.065005
10.1103/PhysRevD.105.065006
10.1103/PhysRevD.105.065010
10.1103/PhysRevD.105.066001
10.1103/PhysRevD.105.066005
10.1103/PhysRevD.105.066006
10.1103/PhysRevD.105.066007
10.1103/PhysRevD.105.066008
10.1103/PhysRevD.105.066009
10.1103/PhysRevD.105.066010
10.1103/PhysRevD.105.L051101
10.1103/PhysRevD.105.L051501
10.1103/PhysRevD.105.L051506
10.1103/PhysRevD.105.L051701

Six PRL articles in APS' report were not included in CERN's repository:
10.1103/PhysRevLett.128.090603
10.1103/PhysRevLett.128.091802
10.1103/PhysRevLett.128.091803
10.1103/PhysRevLett.128.091804
10.1103/PhysRevLett.128.111301
10.1103/PhysRevLett.128.122001

**Comment by drjova** [comment]
all the articles are now in the repo
