### ISSUE TITLE
Extract collaboration

### ISSUE THREAD

**Issue by Dziolas** [SCOAP3/scoap3-next#73]
Add the collaboration extraction to all harvesters and put it in the correct place in article upload workflow

**Comment by Dziolas** [comment]
@oxmynx So where would you like to see this information displayed (on list view and details page)?

**Comment by oxmynx** [comment]
We should only show the collaboration name in the list of search results (and suppress the author names). In the detailed article page, we should add the collaboration name between the author list and the title. Thanks.
